development:
  adapter: postgresql
  encoding: unicode
  database: misquinceflor
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: misquinceflor
  pool: 5
  username: postgres
  password: postgres